name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Render CLI
        run: curl -fsSL https://render.com/download/render-cli.sh | sh
      - name: Deploy to Render
        run: |
          cd src/pybot
          render deploy --service ${{ secrets.RENDER_SERVICE_ID }} --api-key ${{ secrets.RENDER_API_KEY }}